version: "3.4"
x-restart-policy: &restart_policy
  restart: unless-stopped

services:

  # Databases
  database:
    <<: *restart_policy
    image: "postgres:12.2"
    environment:
      POSTGRES_DB: "root"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root!"
    ports:
      - "5432:5432"
    volumes:
      - "root-database:/var/lib/postgresql/data"
    networks:
      - internal

  # Web
  web:
    <<: *restart_policy
    build:
      target: local
      context: root/
    working_dir: /home/ubuntu/webs/root/root
    command: ./bin/run.sh
    depends_on:
      - database
    ports:
      - "3031:3031"
      - "4444:4444"
      - "8000:8000"
    volumes:
      - ./root:/home/ubuntu/webs/root/root
    env_file:
      - root/.env
    networks:
      - internal

  celery_beat:
    <<: *restart_policy
    build:
      context: root/
    image: "cinema_celery_beat"
    command: ./bin/celery_beat_start.sh
    volumes:
      - ./root:/home/ubuntu/webs/root/root
    env_file:
      - root/.env
    depends_on:
      - web
      - redis
    networks:
      - internal

  celery_worker:
    <<: *restart_policy
    build:
      context: root/
    image: "cinema_celery_worker"
    command: ./bin/celery_worker_start.sh
    volumes:
      - ./root:/home/ubuntu/webs/root/root
    env_file:
      - root/.env
    depends_on:
      - web
      - redis
    networks:
      - internal

  celery_flower:
    <<: *restart_policy
    build:
      context: root/
    image: django_celery_example_celery_flower
    command: ./bin/celery_flower_start.sh
    volumes:
      - ./root:/home/ubuntu/webs/root/root
    env_file:
      - root/.env
    depends_on:
      - web
      - redis
    ports:
      - 5557:5555
    networks:
      - internal

  redis:
    <<: *restart_policy
    image: "redis:7.4.2"
    ports:
      - "6389:6379"      
    volumes:
      - "root-redis:/data"
    networks:
     - internal

volumes:
  root-database:
  root-redis:

networks:
  internal:
    driver: bridge
