# Generated by Django 4.2.19 on 2025-03-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=7)),
                ('price', models.FloatField()),
                ('price_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
