# Generated by Django 4.2.19 on 2025-02-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
